define([], function() {
    var config = {
        "group": "14be6bc1d3d64cd8991ffa092b4c9e6c",
        "appid": "",
        "theme": "blueTheme",
        "siteTitle": "San Juan County WA Stormwater Basin Planning",
        "siteBannerImage": "",
        "mapTitle": "",
        "mapSnippet": "",
        "mapItemDescription": "",
        "mapLicenseInfo": "",
        "homeHeading": "",
        "homeSnippet": "A series of web maps designed for Stormwater Basin Planning in San Juan County WA.",
        "homeSideHeading": "",
        "homeSideContent": "Maps here may be used for Stormwater Basin Planning projects. Some maps contain senstive information and will require a login and password. Authorized users can obtain the login and password by emailing SJCGIS@sanjuanco.com.",
        "footerHeading": "",
        "footerDescription": "",
        "footerLogo": "",
        "footerLogoUrl": "",
        "addThisProfileId": "xa-4f3bf72958320e9e",
        "defaultLayout": "list",
        "searchString": "",
        "sortField": "modified",
        "sortOrder": "desc",
        "searchType": "",
        "mapViewer": "simple",
        "paginationSize": 2,
        "galleryItemsPerPage": 9,
        "showProfileUrl": false,
        "showSocialButtons": false,
        "showFooter": true,
        "showBasemapGallery": true,
        "showArcGISBasemaps": false,
        "basemapsGroup": {owner:"npeihl", title:"Base Maps"},
        "showGroupSearch": true,
        "showGroupSort": false,
        "showMapSearch": true,
        "showLayerToggle": true,
        "showLayoutSwitch": true,
        "showOverviewMap": true,
        "showMoreInfo": true,
        "showPagination": true,
        "showArcGISOnlineButton": false,
        "showLicenseInfo": true,
        "showAttribution": true,
        "showComments": false,
        "showRatings": false,
        "showViews": false,
        "showMobileButtons": true,
        "openGalleryItemsNewWindow": true,
        "bannerBackground": "images/ui/banner.png",
        "proxyUrl": "",
        "sharingurl": "",
        "iosAppUrl": "itms://itunes.apple.com/us/app/arcgis/id379687930?mt=8",
        "androidAppUrl": "https://market.android.com/details?id=com.esri.android.client",
        "pointGraphic": "images/ui/bluepoint-21x25.png",
        "sourceCountry": "USA"
    };
    return config;
});
